n = input('Digite um valor: ')
print('Somente alfabetico?')
print(n.isalpha())
print('Somente numerico?')
print(n.isnumeric())
print('E alfanumerico?')
print(n.isalnum())
print('Totalmente maiusculo?')
print(n.isupper())
print('Totalmente minusculo?')
print(n.islower())
print('Capitalizado?')
print(n.istitle())
print('Apenas espacos?')
print(n.isspace())
