algo = input('Digite algo: ')
print('O tipo primitivo desse valor e: ', type(algo))
print('So tem espacos?', algo.isspace())
print('E um numero?', algo.isnumeric())
print('E alfabetico?', algo.isalpha())
print('E alfanumerico?', algo.isalnum())
print('Esta somente em maiusculas?', algo.isupper())
print('Esta somente em minusculas?', algo.islower())
print('Esta capitalizada?', algo.istitle())
